### ISSUE TITLE
No .webp formatted images

### ISSUE THREAD

**Issue by whalderman** [whalderman/search-quality-rater-guidelines-tldr#3]
**Requires \<picture\> elements to be implemented as well.**

Benefits:

- Less network traffic 🚗🚗🚗

Drawbacks:

- Slightly more time-consuming translation process 🕙

**Comment by thewarrman** [comment]
Requires #4

**Comment by whalderman** [comment]
Will not implement -- MozJPEG provides acceptable quality/size ratio.
